### ISSUE TITLE
new interface no longer compiles in odgi due to include order dependence

### ISSUE THREAD

**Issue by ekg** [vgteam/libhandlegraph#11]
I'm unable to get past this strange error:

```
/home/erik/odgi/build/handlegraph-prefix/src/handlegraph/src/include/handlegraph/mutable_path_deletable_handle_graph.hpp:17:85: error: expected class-name befo
re ‘,’ token                                                                                                                                                   
 class MutablePathDeletableHandleGraph : virtual public MutablePathMutableHandleGraph, virtual public DeletableHandleGraph {
```

All I've done is update the git revision of libhandlegraph that I'm pointing to.

How am I using this wrong, and what's changed in the interface since the last working revision? 04688588e4ec840f18af74395d446e868fc13c12

**Comment by ekg** [comment]
The order of includes is important. I had to list these to get the right behavior:

```
#include <handlegraph/handle_graph.hpp>
#include <handlegraph/path_handle_graph.hpp>
#include <handlegraph/mutable_handle_graph.hpp>
#include <handlegraph/mutable_path_handle_graph.hpp>
#include <handlegraph/mutable_path_mutable_handle_graph.hpp>
#include <handlegraph/deletable_handle_graph.hpp>
#include <handlegraph/mutable_path_deletable_handle_graph.hpp>
```

**Comment by jeizenga** [comment]
It might be cleaner if we put MutablePathMutableHandleGraph and MutablePathDeletableHandleGraph in the same .hpp to avoid that...

**Comment by jeizenga** [comment]
Actually, now that I think about it that wouldn't really fix the problem, but I think I know what might
